zuul:
  routes:
    primary:
      sensitiveHeaders: Cookie,Set-Cookie
      path: /**
      url: http://hr.internal.fynesy.com:8080      
      #timeout: 60000
  host:
     socket-timeout-millis: 600000
